name: CI/CD Dev
on:
  push:
    branches:
      - develop
jobs:
  website:
    name: "Website: Build and Test"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Setup git:// protocol workarounds
      run: git config --global url.https://github.com/.insteadOf git://github.com/
    - run: npm install
    - run: node scripts/version.js
    - run: npm run lint
    - run: npm run build:ci
    # Tests are currently disabled: there arn't a lot and they are just broken and anoying.
    #- run: npm run test:ci
    #- run: npm run e2e
