name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  contract:
    name: "Contract: Build and Test"
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: ./contract
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Setup git:// protocol workarounds
      run: git config --global url.https://github.com/.insteadOf git://github.com/
    - run: npm install
    - run: npm run build
    - run: npm run test
  website:
    needs: contract
    name: "Website: Build and Test"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Setup git:// protocol workarounds
      run: git config --global url.https://github.com/.insteadOf git://github.com/
    - run: npm install
    - run: npm run build # later change to build:ci again
    - run: npm run test # later change to test:ci again
    #- run: npm run e2e
    - name: Deploy to IPFS host
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "shop/dist/w3shop"
        target: "ipfs/export/w3shop"
# Setup the deployment in a seperate job
  # deploy:
    # runs-on: ubuntu-latest
    # needs: build
    # steps:
      # Deploy to my IPFS node
      #- name: Checkout
      #  uses: actions/checkout@v1
      #- name: Download build
      #  uses: actions/download-artifact@v1
      #  with:
      #    name: deploy_dist
      #- name: Deploy to GitHub Pages
      #  uses: JamesIves/github-pages-deploy-action@releases/v3
      #  with:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    BRANCH: gh-pages
      #    FOLDER: deploy_dist/angular-demo