name: Deploy Shop
on:
  push:
    branches:
      - main
jobs:
  build:
    name: "Shop: Build and test"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shop
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Setup git:// protocol workarounds
      run: git config --global url.https://github.com/.insteadOf git://github.com/
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
   # - name: Archive build
    #  if: success()
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: deploy_dist
    #    path: shop/dist
    - name: Deploy shop to IPFS host
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "shop/dist"
        target: "ipfs/export"
  #deploy:
  #  runs-on: ubuntu-latest
  #  needs: build
  #  steps:
      # Deploy to my IPFS node
      #- name: Checkout
      #  uses: actions/checkout@v1
      #- name: Download build
      #  uses: actions/download-artifact@v1
      #  with:
      #    name: deploy_dist
      #- name: Deploy to GitHub Pages
      #  uses: JamesIves/github-pages-deploy-action@releases/v3
      #  with:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    BRANCH: gh-pages
      #    FOLDER: deploy_dist/angular-demo