name: Setup Environment

on:
  workflow_call:

jobs:
  example_job:
    name: Setup the Environment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node 12.x
      uses: actions/setup-node@v3
      with:
        node-version: '12.x'
    - name: Setup git:// protocol workarounds
      run: git config --global url.https://github.com/.insteadOf git://github.com/